services:
  postgres_db:
    image: postgres:18
    container_name: conectatech_pg18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-conectatech_db}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-DBAjunior.2020}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./sql/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./sql/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql:ro
      - ./sql:/scripts:ro

volumes:
  pgdata: